import json
import os


def generate_analysis_notebook(
    results_dir: str,
    summary: dict,
    history_csv_path: str,
    summary_json_path: str,
):
    nb_path = os.path.join(results_dir, "analysis.ipynb")

    notebook = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "# Analisis de entrenamiento Tiny ImageNet\n",
                    "\n",
                    "Notebook generado automaticamente.\n",
                    "\n",
                    "Incluye:\n",
                    "- carga de historial y resumen\n",
                    "- metricas principales\n",
                    "- mejor epoch\n",
                    "- curvas de cost, accuracy, tiempo y learning rate\n",
                    "- tabla resumen final\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "import json\n",
                    "import pandas as pd\n",
                    "import matplotlib.pyplot as plt\n",
                    "from pathlib import Path\n",
                    "\n",
                    f'csv_file = Path(r"{history_csv_path}")\n',
                    f'json_file = Path(r"{summary_json_path}")\n',
                    "\n",
                    "df = pd.read_csv(csv_file)\n",
                    "with open(json_file, 'r', encoding='utf-8') as f:\n",
                    "    summary = json.load(f)\n",
                    "\n",
                    "df = df.sort_values('epoch').reset_index(drop=True)\n",
                    "\n",
                    "if 'lr' not in df.columns:\n",
                    "    df['lr'] = None\n",
                    "\n",
                    "df['generalization_gap'] = df['train'] - df['test']\n",
                    "df['test_gain'] = df['test'].diff().fillna(0)\n",
                    "df['cost_delta'] = df['cost'].diff().fillna(0)\n",
                    "\n",
                    "df.head()\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## Resumen del experimento\n",
                    "\n",
                    f"- Arquitectura: {summary.get('arch', 'N/A')}\n",
                    f"- Pretrained: {summary.get('pretrained', 'N/A')}\n",
                    f"- Freeze backbone: {summary.get('freeze_backbone', 'N/A')}\n",
                    f"- Optimizer: {summary.get('optimizer', 'N/A')}\n",
                    f"- Epochs completadas: {summary.get('epochs_completed', 'N/A')}\n",
                    f"- Workers: {summary.get('num_workers', 'N/A')}\n",
                    f"- Local epochs: {summary.get('local_epochs', 'N/A')}\n",
                    f"- LR inicial: {summary.get('lr', 'N/A')}\n",
                    f"- LR step size: {summary.get('lr_step_size', 'N/A')}\n",
                    f"- LR gamma: {summary.get('lr_gamma', 'N/A')}\n",
                    f"- Batch size train: {summary.get('train_batch_size', 'N/A')}\n",
                    f"- Batch size val: {summary.get('val_batch_size', 'N/A')}\n",
                    f"- Image size: {summary.get('image_size', 'N/A')}\n",
                    f"- Device: {summary.get('device', 'N/A')}\n",
                    f"- Mejor test: {summary.get('best_test', 'N/A')}\n",
                    f"- Mejor epoch: {summary.get('best_epoch', 'N/A')}\n",
                    f"- Tiempo total: {summary.get('total_time_sec', 'N/A')} s\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "print('Columnas disponibles:')\n",
                    "print(df.columns.tolist())\n",
                    "print()\n",
                    "print('Primeras filas:')\n",
                    "display(df.head())\n",
                    "print()\n",
                    "print('Ultimas filas:')\n",
                    "display(df.tail())\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "best_idx = df['test'].idxmax()\n",
                    "best_row = df.loc[best_idx]\n",
                    "last_row = df.iloc[-1]\n",
                    "\n",
                    "print('=== MEJOR EPOCH ===')\n",
                    "print(f\"Epoch: {int(best_row['epoch'])}\")\n",
                    "print(f\"Cost: {best_row['cost']:.6f}\")\n",
                    "print(f\"Train: {best_row['train']:.6f}\")\n",
                    "print(f\"Test: {best_row['test']:.6f}\")\n",
                    "print(f\"Gap train-test: {best_row['generalization_gap']:.6f}\")\n",
                    "if pd.notna(best_row['lr']):\n",
                    "    print(f\"LR: {best_row['lr']:.8f}\")\n",
                    "print()\n",
                    "print('=== ULTIMA EPOCH ===')\n",
                    "print(f\"Epoch: {int(last_row['epoch'])}\")\n",
                    "print(f\"Cost: {last_row['cost']:.6f}\")\n",
                    "print(f\"Train: {last_row['train']:.6f}\")\n",
                    "print(f\"Test: {last_row['test']:.6f}\")\n",
                    "print(f\"Gap train-test: {last_row['generalization_gap']:.6f}\")\n",
                    "print(f\"Epoch time: {last_row['epoch_time']:.2f} s\")\n",
                    "print(f\"Total time: {last_row['total_time']:.2f} s\")\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "summary_table = pd.DataFrame([\n",
                    "    {\n",
                    "        'metric': 'best_test',\n",
                    "        'value': float(df['test'].max())\n",
                    "    },\n",
                    "    {\n",
                    "        'metric': 'best_epoch',\n",
                    "        'value': int(df.loc[df['test'].idxmax(), 'epoch'])\n",
                    "    },\n",
                    "    {\n",
                    "        'metric': 'final_test',\n",
                    "        'value': float(df.iloc[-1]['test'])\n",
                    "    },\n",
                    "    {\n",
                    "        'metric': 'final_train',\n",
                    "        'value': float(df.iloc[-1]['train'])\n",
                    "    },\n",
                    "    {\n",
                    "        'metric': 'final_cost',\n",
                    "        'value': float(df.iloc[-1]['cost'])\n",
                    "    },\n",
                    "    {\n",
                    "        'metric': 'total_time_sec',\n",
                    "        'value': float(df.iloc[-1]['total_time'])\n",
                    "    },\n",
                    "])\n",
                    "\n",
                    "summary_table\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## Graficas principales\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "plt.figure(figsize=(9,5))\n",
                    "plt.plot(df['epoch'], df['cost'], marker='o', label='Cost')\n",
                    "plt.axvline(df.loc[df['test'].idxmax(), 'epoch'], linestyle='--', label='Best epoch')\n",
                    "plt.title('Cost por epoch')\n",
                    "plt.xlabel('Epoch')\n",
                    "plt.ylabel('Cost')\n",
                    "plt.grid(True)\n",
                    "plt.legend()\n",
                    "plt.tight_layout()\n",
                    "plt.show()\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "plt.figure(figsize=(9,5))\n",
                    "plt.plot(df['epoch'], df['train'], marker='o', label='Train accuracy')\n",
                    "plt.plot(df['epoch'], df['test'], marker='s', label='Test accuracy')\n",
                    "plt.axvline(df.loc[df['test'].idxmax(), 'epoch'], linestyle='--', label='Best epoch')\n",
                    "plt.title('Accuracy por epoch')\n",
                    "plt.xlabel('Epoch')\n",
                    "plt.ylabel('Accuracy')\n",
                    "plt.grid(True)\n",
                    "plt.legend()\n",
                    "plt.tight_layout()\n",
                    "plt.show()\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "plt.figure(figsize=(9,5))\n",
                    "plt.plot(df['epoch'], df['generalization_gap'], marker='o')\n",
                    "plt.axhline(0, linestyle='--')\n",
                    "plt.title('Gap de generalizacion (train - test)')\n",
                    "plt.xlabel('Epoch')\n",
                    "plt.ylabel('Gap')\n",
                    "plt.grid(True)\n",
                    "plt.tight_layout()\n",
                    "plt.show()\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "plt.figure(figsize=(9,5))\n",
                    "plt.plot(df['epoch'], df['epoch_time'], marker='o', label='Epoch time')\n",
                    "plt.plot(df['epoch'], df['total_time'], marker='s', label='Total time')\n",
                    "plt.title('Tiempo de entrenamiento')\n",
                    "plt.xlabel('Epoch')\n",
                    "plt.ylabel('Segundos')\n",
                    "plt.grid(True)\n",
                    "plt.legend()\n",
                    "plt.tight_layout()\n",
                    "plt.show()\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "if df['lr'].notna().any():\n",
                    "    plt.figure(figsize=(9,5))\n",
                    "    plt.plot(df['epoch'], df['lr'], marker='o')\n",
                    "    plt.title('Learning Rate por epoch')\n",
                    "    plt.xlabel('Epoch')\n",
                    "    plt.ylabel('LR')\n",
                    "    plt.grid(True)\n",
                    "    plt.tight_layout()\n",
                    "    plt.show()\n",
                    "else:\n",
                    "    print('No hay columna lr disponible para graficar.')\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## Analisis de progreso\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "progress_table = pd.DataFrame([\n",
                    "    {\n",
                    "        'metric': 'delta_train',\n",
                    "        'value': float(df.iloc[-1]['train'] - df.iloc[0]['train'])\n",
                    "    },\n",
                    "    {\n",
                    "        'metric': 'delta_test',\n",
                    "        'value': float(df.iloc[-1]['test'] - df.iloc[0]['test'])\n",
                    "    },\n",
                    "    {\n",
                    "        'metric': 'delta_cost',\n",
                    "        'value': float(df.iloc[-1]['cost'] - df.iloc[0]['cost'])\n",
                    "    },\n",
                    "    {\n",
                    "        'metric': 'best_minus_final_test',\n",
                    "        'value': float(df['test'].max() - df.iloc[-1]['test'])\n",
                    "    },\n",
                    "])\n",
                    "\n",
                    "progress_table\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "print('Top 10 epochs por test accuracy:')\n",
                    "display(df.sort_values('test', ascending=False).head(10))\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "print('Epochs con mayor ganancia en test:')\n",
                    "display(df.sort_values('test_gain', ascending=False).head(10))\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## Conclusiones automaticas\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "best_test = float(df['test'].max())\n",
                    "final_test = float(df.iloc[-1]['test'])\n",
                    "best_epoch = int(df.loc[df['test'].idxmax(), 'epoch'])\n",
                    "final_gap = float(df.iloc[-1]['generalization_gap'])\n",
                    "cost_trend = float(df.iloc[-1]['cost'] - df.iloc[0]['cost'])\n",
                    "\n",
                    "print(f'Mejor test accuracy: {best_test:.6f} en epoch {best_epoch}')\n",
                    "print(f'Test final: {final_test:.6f}')\n",
                    "print(f'Gap final train-test: {final_gap:.6f}')\n",
                    "print(f'Cambio total en cost: {cost_trend:.6f}')\n",
                    "\n",
                    "if final_test < best_test:\n",
                    "    print('Observacion: el mejor rendimiento ocurrio antes de la ultima epoch.')\n",
                    "\n",
                    "if final_gap > 0.15:\n",
                    "    print('Observacion: puede haber sobreajuste porque train esta bastante por encima de test.')\n",
                    "\n",
                    "if cost_trend < 0:\n",
                    "    print('Observacion: el cost total bajo respecto al inicio, lo cual es una buena senal.')\n",
                ],
            },
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.x",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }

    with open(nb_path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=2, ensure_ascii=False)

    print(f"Notebook generado: {nb_path}")